### ISSUE TITLE
Operators in compiler still use llvmlite

### ISSUE THREAD

**Issue by ActuallyEnbeon** [aurorusidk/starling#28]
All operators (see `build_binary` and `build_unary` in the compiler) use llvmlite syntax rather than llvmcpy, and thus code using any binary or unary operator cannot compile

**Comment by aurorusidk** [comment]
@ActuallyEnbeon this is fixed by 9661dd0ba9336a30e15608fbb4f37f498ca44c67, 770b03dd50c4d1a815fcb40297500ce30d04e3d0, 6d16f8c7a2e8188b7a94c89d8055d4081336945c, ee15e8d3f96b2a91c351fc61130e85818506e2ae right?
